version: "3"

services:
  mysql:
    image: mariadb:10.7.8
    container_name: mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: 'test_db'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
      # Uncomment the two options below first to setup storage permissions, there will be errors.
#    command: sh -c "/scripts/verify_storage.sh"
#    user: root
    volumes:
      - db-data:/data/db
      - db-logs:/data/logs
      - $PWD/mariadb.cnf:/etc/mysql/mariadb.cnf
      - $PWD/scripts:/scripts
    ports:
      - "127.0.0.1:3306:3306/tcp"    
volumes:
  db-data:
  db-logs:
